version: '3.3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3030:3030
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - mysql